# Generated by Django 4.1.4 on 2022-12-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('rooms', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('category', models.CharField(choices=[('house', 'house'), ('office', 'office'), ('shop', 'shop'), ('kibanda', 'kibanda')], default=('house', 'house'), max_length=200)),
                ('facilities', models.TextField()),
                ('more_info', models.TextField()),
            ],
            options={
                'ordering': ['description'],
            },
        ),
    ]
