# Generated by Django 4.1.4 on 2022-12-29 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kibhub', '0002_property_contacts_alter_property_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img')),
                ('property_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kibhub.property')),
            ],
        ),
    ]
